"""
music_age.py
------------
Stage 3 of the "My Music Age" project.

This module takes the cleaned listening DataFrame from Stage 2,
enriches it with release years from a Kaggle Spotify catalogue,
and calculates the user's Music Age profile.

Public API:
    enrich_with_catalogue(listening_df, catalogue_path) -> (enriched_df, stats)
    compute_music_age(enriched_df, reference_year=None) -> dict
    era_distribution(enriched_df) -> pd.DataFrame
    top_track_per_decade(enriched_df) -> pd.DataFrame
    assign_era_profile(era_dist) -> str

The contract with Stage 2:
    Input DataFrame must have columns:
        artist, track, artist_key, track_key, ms_played, minutes_played
"""

from __future__ import annotations

from pathlib import Path
from typing import Union

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# 1. CATALOGUE LOADING + MERGING
# ---------------------------------------------------------------------------

def _normalise_key(series: pd.Series) -> pd.Series:
    """
    Apply the same normalisation we used on listening data in Stage 2:
    lowercase + strip + collapse internal whitespace.

    Kept as a private helper so listening and catalogue keys are
    generated by the *exact same logic* — this is critical for merge hit-rate.
    """
    return (
        series.astype(str)
              .str.strip()
              .str.lower()
              .str.replace(r"\s+", " ", regex=True)
    )


def load_catalogue(path: Union[str, Path]) -> pd.DataFrame:
    """
    Load the Kaggle Spotify catalogue CSV.

    Expected columns (from amitanshjoshi/spotify-1million-tracks):
        artist_name, track_name, track_id, popularity, year, genre, ...

    We only keep the fields we need for Music Age:
        artist_name -> artist_key
        track_name  -> track_key
        year        -> release_year

    If a track appears multiple times in the catalogue (remasters,
    compilations), we keep the *earliest* release year — that's usually
    the real one.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Catalogue not found: {path}")

    # Read only the columns we need — the catalogue has 20 cols but we
    # only care about 3. Saves memory on the real 1M-row file.
    wanted = ["artist_name", "track_name", "year"]
    df = pd.read_csv(path, usecols=wanted)

    # Clean up any missing or weird years
    df = df.dropna(subset=["artist_name", "track_name", "year"])
    df["year"] = pd.to_numeric(df["year"], errors="coerce")
    df = df.dropna(subset=["year"])
    df["year"] = df["year"].astype(int)

    # Build merge keys using the exact same normalisation as Stage 2
    df["artist_key"] = _normalise_key(df["artist_name"])
    df["track_key"]  = _normalise_key(df["track_name"])

    # A track can appear multiple times in the catalogue (remaster,
    # anniversary edition, compilation). Keep the earliest release year,
    # which is almost always the true original year.
    df = (df.sort_values("year")
            .drop_duplicates(subset=["artist_key", "track_key"], keep="first")
            .rename(columns={"year": "release_year"})
            [["artist_key", "track_key", "release_year"]])

    return df.reset_index(drop=True)


def enrich_with_catalogue(
    listening_df: pd.DataFrame,
    catalogue_path: Union[str, Path],
) -> tuple[pd.DataFrame, dict]:
    """
    Join listening data with the catalogue to recover release years.

    Returns:
        enriched_df  — listening_df + 'release_year' column
                       (NaN for tracks not found in catalogue)
        stats        — dict with match-rate statistics

    Uses a LEFT join so we don't lose any listening rows if a track
    isn't in the catalogue. Tracks without a release year will be
    excluded later when Music Age is calculated, but remain available
    for other analyses (like total listening time).
    """
    catalogue = load_catalogue(catalogue_path)

    enriched = listening_df.merge(
        catalogue,
        on=["artist_key", "track_key"],
        how="left",
    )

    # Compute match statistics — useful for the final report and
    # for catching data-quality issues early.
    total_plays       = len(enriched)
    matched_plays     = enriched["release_year"].notna().sum()
    unique_tracks     = enriched.groupby(["artist_key", "track_key"]).ngroups
    unique_matched    = (
        enriched.dropna(subset=["release_year"])
                .groupby(["artist_key", "track_key"]).ngroups
    )

    stats = {
        "total_plays":          int(total_plays),
        "matched_plays":        int(matched_plays),
        "match_rate_plays":     round(matched_plays / total_plays * 100, 1),
        "unique_tracks":        int(unique_tracks),
        "unique_matched":       int(unique_matched),
        "match_rate_tracks":    round(unique_matched / unique_tracks * 100, 1),
    }

    return enriched, stats


# ---------------------------------------------------------------------------
# 2. MUSIC AGE COMPUTATION
# ---------------------------------------------------------------------------

def compute_music_age(
    enriched_df: pd.DataFrame,
    reference_year: int | None = None,
) -> dict:
    """
    Compute the user's "Music Age" two ways:

    1. WEIGHTED age  — weighted by play count. This tells you how old
       the music that you ACTUALLY LISTEN TO is, on average. Heavy-
       rotation tracks pull this number strongly.

    2. LIBRARY age   — each unique track counted once. This tells you
       how old your TASTE is — the span of music you ever play,
       ignoring repetition.

    The two numbers diverge when (for example) you own a lot of oldies
    but play them rarely — LIBRARY age will be higher than WEIGHTED.

    Args:
        enriched_df     — output of enrich_with_catalogue()
        reference_year  — year to measure age against (defaults to current)

    Returns a dict with both ages, plus the raw mean release years and
    the number of plays/tracks that were usable.
    """
    if reference_year is None:
        reference_year = pd.Timestamp.now().year

    # Only plays where we know the release year count toward Music Age
    usable = enriched_df.dropna(subset=["release_year"]).copy()
    if usable.empty:
        return {
            "music_age_weighted": None,
            "music_age_library":  None,
            "reference_year":     reference_year,
            "usable_plays":       0,
            "usable_tracks":      0,
            "note":               "No tracks could be matched to release years.",
        }

    usable["release_year"] = usable["release_year"].astype(int)

    # --- 1. WEIGHTED mean (every play counts) ---
    # Each play contributes its own release_year to the average.
    # Songs played 500 times count 500 times more than songs played once.
    #
    # Weighted-mean formula, written using only basic NumPy operations
    # (multiplication, sum, division) — all covered in Module 2 L18.
    # Equivalent to: sum(year * play_time) / sum(play_time).
    years           = usable["release_year"].to_numpy()
    weights         = usable["ms_played"].to_numpy()
    mean_release_w  = np.sum(years * weights) / np.sum(weights)

    # --- 2. LIBRARY mean (each unique track once) ---
    unique_tracks = (
        usable.drop_duplicates(subset=["artist_key", "track_key"])
              ["release_year"]
    )
    mean_release_l = unique_tracks.mean()

    return {
        "music_age_weighted":   round(reference_year - mean_release_w, 1),
        "music_age_library":    round(reference_year - mean_release_l, 1),
        "mean_release_weighted": round(float(mean_release_w), 1),
        "mean_release_library":  round(float(mean_release_l), 1),
        "reference_year":       reference_year,
        "usable_plays":         int(len(usable)),
        "usable_tracks":        int(len(unique_tracks)),
    }


# ---------------------------------------------------------------------------
# 3. ERA DISTRIBUTION + PROFILE LABEL
# ---------------------------------------------------------------------------

def era_distribution(enriched_df: pd.DataFrame) -> pd.DataFrame:
    """
    Break down total listening time by decade.

    Returns a DataFrame:
        decade  (e.g. "1970s", "2020s")
        minutes
        pct_of_total
        play_count

    Decades are derived from release_year: 1975 -> "1970s", 2022 -> "2020s".
    """
    usable = enriched_df.dropna(subset=["release_year"]).copy()
    if usable.empty:
        return pd.DataFrame(columns=["decade", "minutes", "pct_of_total",
                                     "play_count"])

    usable["release_year"] = usable["release_year"].astype(int)
    # 1985 → "1980s", 2023 → "2020s"
    usable["decade"] = (usable["release_year"] // 10 * 10).astype(str) + "s"

    agg = (usable.groupby("decade")
                 .agg(minutes=("minutes_played", "sum"),
                      play_count=("minutes_played", "size"))
                 .reset_index())

    total_minutes = agg["minutes"].sum()
    agg["pct_of_total"] = (agg["minutes"] / total_minutes * 100).round(1)
    agg["minutes"] = agg["minutes"].round(1)

    # Sort decades chronologically
    agg = agg.sort_values("decade").reset_index(drop=True)
    return agg


def top_track_per_decade(
    enriched_df: pd.DataFrame,
    n: int = 1,
) -> pd.DataFrame:
    """
    For each decade, find the top-`n` tracks by total listening time.
    Returns a tidy DataFrame with: decade, artist, track, minutes.
    """
    usable = enriched_df.dropna(subset=["release_year"]).copy()
    if usable.empty:
        return pd.DataFrame(columns=["decade", "artist", "track", "minutes"])

    usable["release_year"] = usable["release_year"].astype(int)
    usable["decade"] = (usable["release_year"] // 10 * 10).astype(str) + "s"

    # Aggregate total minutes per (decade, artist, track), then take top N per decade
    by_track = (usable.groupby(["decade", "artist", "track"])["minutes_played"]
                       .sum()
                       .round(1)
                       .reset_index(name="minutes"))

    top = (by_track.sort_values(["decade", "minutes"], ascending=[True, False])
                    .groupby("decade")
                    .head(n)
                    .reset_index(drop=True))
    return top


def assign_era_profile(era_dist: pd.DataFrame) -> str:
    """
    Assign a descriptive label based on the shape of the era distribution.

    The rules (simple, explainable — not ML):
      - If ONE decade > 50%            → "{Decade} Loyalist"   e.g. "2010s Loyalist"
      - If 4+ decades each have > 10%  → "Decade Hopper"
      - If the top 2 decades are the latest two (≥ 60% combined)
                                       → "Future Forward"
      - If the top 2 decades are 1960s-80s (≥ 60% combined)
                                       → "Vintage Soul"
      - Otherwise                      → "Balanced Listener"

    Returns a human-readable label string.
    """
    if era_dist.empty:
        return "No Profile — Not Enough Data"

    # 1. Single-decade loyalist
    top = era_dist.loc[era_dist["pct_of_total"].idxmax()]
    if top["pct_of_total"] > 50:
        return f"{top['decade']} Loyalist"

    # 2. Decade hopper
    significant = era_dist[era_dist["pct_of_total"] > 10]
    if len(significant) >= 4:
        return "Decade Hopper"

    # 3. Future forward — heavy in 2010s + 2020s
    modern = era_dist[era_dist["decade"].isin(["2010s", "2020s"])]
    if modern["pct_of_total"].sum() >= 60:
        return "Future Forward"

    # 4. Vintage soul — heavy in pre-1990 music
    vintage = era_dist[era_dist["decade"].isin(["1960s", "1970s", "1980s"])]
    if vintage["pct_of_total"].sum() >= 60:
        return "Vintage Soul"

    # 5. Fallback
    return "Balanced Listener"


# ---------------------------------------------------------------------------
# Quick smoke test when run directly
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    from data_pipeline import load_listening_history, clean_listening_history

    print("Loading listening data…")
    raw   = load_listening_history("StreamingHistory_sample.json")
    clean = clean_listening_history(raw)

    print("\nEnriching with catalogue…")
    enriched, stats = enrich_with_catalogue(clean, "catalogue/spotify_data.csv")
    for k, v in stats.items():
        print(f"  {k:20s} {v}")

    print("\nMusic Age:")
    age = compute_music_age(enriched)
    for k, v in age.items():
        print(f"  {k:25s} {v}")

    print("\nEra distribution:")
    dist = era_distribution(enriched)
    print(dist.to_string(index=False))

    print(f"\nEra profile: {assign_era_profile(dist)}")

    print("\nTop track per decade:")
    top = top_track_per_decade(enriched)
    print(top.to_string(index=False))
